openapi: 3.0.0
info:
  version: 1.0.0
  title: 'SCORE Project'
  description: 'Predict 10-year risk of cardiovascular disease'
servers:
  - url: '/99999/score/v1/'
    description: 'Predict 10-year risk of cardiovascular disease bundle.v1'
tags:
  - name: KO Endpoints
    description: Score Endpoints
paths:
  /score:
    post:
      tags:
        - KO Endpoints
      description: Hello
      operationId: hello
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
components:
  schemas:
    input:
      required:
        - name
        - language
      properties:
        name:
          type: string
          example: Carol
        language:
          type: string
          example: spanish
    output:
      required:
        - result
      properties:
        result:
          type: object
          additionalProperties:
            type: object
