openapi: 3.0.0
info:
  version: 1.0.0
  title: 'SCORE Project'
  description: 'Predict 10-year risk of cardiovascular disease'
servers:
  - url: '/99999/score/v1/'
    description: 'Predict 10-year risk of cardiovascular disease'
tags:
  - name: KO Endpoints
    description: Score Endpoints
paths:
  /score:
    post:
      tags:
        - KO Endpoints
      description: 'Predict 10-year risk of cardiovascular disease'
      operationId: score
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
components:
  schemas:
    input:
      required:
        - sex
        - age
        - smoke
        - risk
        - sbp
        - chol
      properties:
        sex:
          type: string
          enum: [M, F]
        age:
          type: integer
        smoke:
          type: boolean
        risk:
          type: string
          enum: [high, low]
        sbp:
          type: integer
          minimum: 120
          maximum: 180
        chol:
          type: number
      example:
        age: 45
        sex: F
        smoke: false
        risk: low
        sbp: 120
        chol: 4
    output:
      required:
        - result
      properties:
        result:
          type: object
          additionalProperties:
            type: object
